---
- hosts: timetracker
  tasks:
    - name: Add node repository
      action: apt_repository repo='ppa:chris-lea/node.js'
    - name: Install packages
      action: apt pkg={{ item }} state=installed update_cache=true
      with_items: 
      - nginx
      - nodejs
      - mongodb
    - name: Set nginx default site
      action: copy src=configs/nginx.default dest=/etc/nginx/sites-enabled/default
      notify:
      - restart nginx
    - name: ensure nginx is running
      service: name=nginx state=started
    - name: install project dependencys
      npm: path=/timetracker
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
